baseURL = "http://info.ikebuku.ro/"
languageCode = "ja-JP"
title = "Mastodon Ikebukuro Division Information"
theme = "ananke"
enableGitInfo = true

[params]
  AuthorName = "cybergene"
  GitHubUser = "cyber-gene"

[permalinks]
  posts = "/:year/:month/:title/"